GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImZ1bGxuYW1lIjoiQWhtYWQgUmlma2kgQXlhbGEiLCJuaWNrbmFtZSI6ImRzIiwiZW1haWwiOiJheWFsYXJpZmtpQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDgyMTg0OTUyNTgyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTcxNjI4NDIsImV4cCI6MTcxNzE2MjkwMn0.PXDvEZRqkyajaoiHDFSUw0ZoRqOxwFsdrthsWWSG5q4
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "fullname": "John Doe",
    "nickname": "johndoe123",
    "email": "johndoe@example.com",
    "phoneNumber": "123456789",
    "password": "password123",
    "confirmPassword": "password123"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ayalarifki@gmail.com",
    "password": "ayala123"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImZ1bGxuYW1lIjoiQWhtYWQgUmlma2kgQXlhbGEiLCJuaWNrbmFtZSI6ImRzIiwiZW1haWwiOiJheWFsYXJpZmtpQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDgyMTg0OTUyNTgyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTcxNjIwMjMsImV4cCI6MTcxNzI0ODQyM30.L3v1SBORvLqoOC6FjWaH4NUKoEBjmbArEiXlWcgFo2Q

###
GET http://localhost:5000/makanan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImZ1bGxuYW1lIjoiQWhtYWQgUmlma2kgQXlhbGEiLCJuaWNrbmFtZSI6ImRzIiwiZW1haWwiOiJheWFsYXJpZmtpQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDgyMTg0OTUyNTgyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTcxNjIwMjMsImV4cCI6MTcxNzI0ODQyM30.L3v1SBORvLqoOC6FjWaH4NUKoEBjmbArEiXlWcgFo2Q

###
GET http://localhost:5000/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImZ1bGxuYW1lIjoiQWhtYWQgUmlma2kgQXlhbGEiLCJuaWNrbmFtZSI6ImRzIiwiZW1haWwiOiJheWFsYXJpZmtpQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDgyMTg0OTUyNTgyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTc0MDAxNDAsImV4cCI6MTcxNzQ4NjU0MH0.l6tGrN_zh3W7VrSyGKjFRVRwO8SHe1J3jguu389PCT0
